### ISSUE TITLE
Consider adding Jaeger

### ISSUE THREAD

**Issue by yurishkuro** [gophersgang/non-trivial-go-apps#1]
http://github.com/uber/jaeger

**Comment by mindreframer** [comment]
hi @yurishkuro, done. 
thx!

**Comment by yurishkuro** [comment]
👍 

btw, the number of stars seems to be pulled incorrectly, not just for Jaeger, but for other projects as well.

**Comment by mindreframer** [comment]
Oh, you are right... will fix it next days... thx!
